# Generated by Django 5.2.15 on 2026-07-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=20)),
                ('date_heure', models.DateTimeField()),
                ('source', models.CharField(choices=[('badge', 'Badge'), ('manuel', 'Manuel'), ('biometrie', 'Biométrie')], default='badge', max_length=20)),
                ('periode', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='agents.agent')),
            ],
            options={
                'db_table': 'pointages',
                'indexes': [models.Index(fields=['agent', 'periode'], name='pointages_agent_i_fed7d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('nombre_passages', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('conge', 'Congé')], max_length=20, null=True)),
                ('source_calcul', models.CharField(blank=True, max_length=100, null=True)),
                ('donnees_brutes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='agents.agent')),
            ],
            options={
                'db_table': 'presences',
                'indexes': [models.Index(fields=['agent', 'date'], name='presences_agent_i_489b3d_idx')],
            },
        ),
    ]
