# Generated by Django 5.2.15 on 2026-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('fonction', models.CharField(blank=True, max_length=150, null=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('sorti', 'Sorti')], default='nouveau', max_length=20)),
                ('carte_esia', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=3)),
                ('cnaps', models.CharField(blank=True, max_length=50, null=True)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance')], default='CDI', max_length=20)),
                ('superieur_hierarchique', models.CharField(default='team-leader', max_length=100)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Annuel'), ('maladie', 'Maladie'), ('exceptionnel', 'Exceptionnel'), ('formation', 'Formation'), ('maternite', 'Maternité'), ('paternite', 'Paternité')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_ouverte', models.FloatField(help_text='Nombre de jours ouvrés')),
                ('duree_reelle', models.PositiveIntegerField(blank=True, help_text='Nombre de jours calendaires', null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True, null=True)),
                ('annee_reference', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conges',
            },
        ),
        migrations.CreateModel(
            name='ContactUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('lien_parente', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts_urgence',
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diplomes',
            },
        ),
        migrations.CreateModel(
            name='FormationSuivie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'formations_suivies',
            },
        ),
        migrations.CreateModel(
            name='OffboardingTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('tache', models.CharField(max_length=255)),
                ('statut', models.CharField(default='a_faire', max_length=50)),
            ],
            options={
                'db_table': 'offboarding_taches',
            },
        ),
        migrations.CreateModel(
            name='OnboardingTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('tache', models.CharField(max_length=255)),
                ('statut', models.CharField(default='a_faire', max_length=50)),
            ],
            options={
                'db_table': 'onboarding_taches',
            },
        ),
        migrations.CreateModel(
            name='RibBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_banque', models.CharField(max_length=100)),
                ('code_banque', models.CharField(max_length=20)),
                ('code_agence', models.CharField(max_length=20)),
                ('numero_compte', models.CharField(max_length=50)),
                ('cle_rib', models.CharField(max_length=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rib_bancaires',
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('total_jours', models.FloatField(default=30)),
                ('jours_pris', models.FloatField(default=0)),
                ('jours_restants', models.FloatField(default=30)),
                ('jours_en_attente', models.FloatField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'soldes_conges',
            },
        ),
    ]
