# Generated by Django 5.2.15 on 2026-07-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agents', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='poste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='workspaces.poste'),
        ),
        migrations.AddField(
            model_name='agent',
            name='profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='accounts.profil'),
        ),
        migrations.AddField(
            model_name='agent',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='workspaces.projet'),
        ),
        migrations.AddField(
            model_name='conge',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='conge',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacturgence',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_urgence', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='formationsuivie',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_suivies', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='offboardingtache',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_taches', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='onboardingtache',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_taches', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='ribbancaire',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rib_bancaire', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='soldeconge',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conges', to='agents.agent'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['agent', 'annee_reference'], name='conges_agent_i_36cd04_idx'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['statut'], name='conges_statut_cbbfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='conge',
            index=models.Index(fields=['date_debut', 'date_fin'], name='conges_date_de_755aca_idx'),
        ),
        migrations.AddConstraint(
            model_name='soldeconge',
            constraint=models.UniqueConstraint(fields=('agent', 'annee'), name='uniq_solde_agent_annee'),
        ),
    ]
