# Generated by Django 5.2.15 on 2026-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='statut_presence',
            field=models.CharField(choices=[('present', 'Présent'), ('abscent', 'Abscent'), ('conges', 'Congé'), ('tt', 'Télétravail'), ('nouveau', 'Nouveau'), ('en-attente', 'En attente')], default='nouveau', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='carte_esia',
            field=models.CharField(choices=[('oui', 'Oui'), ('en-cours', 'En cours'), ('non', 'Non')], default='non', max_length=20),
        ),
    ]
