# Generated by Django 5.2.15 on 2026-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_statut_presence_alter_agent_carte_esia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='superieur_hierarchique',
            field=models.CharField(choices=[('team-leader', 'Team Leader'), ('direction-generale', 'Direction Générale')], default='team-leader', max_length=20),
        ),
    ]
