# Generated by Django 5.2.15 on 2026-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/%Y/%m/'),
        ),
    ]
