# Generated by Django 5.2.15 on 2026-07-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('numero', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('maintenance', 'Maintenance'), ('hors_service', 'Hors service')], default='libre', max_length=20)),
            ],
            options={
                'db_table': 'postes',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('total_postes', models.PositiveIntegerField(default=0)),
                ('postes_bas', models.PositiveIntegerField(default=0)),
                ('postes_haut', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'racks',
            },
        ),
        migrations.CreateModel(
            name='AffectationPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_postes', to='agents.agent')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='workspaces.poste')),
            ],
            options={
                'db_table': 'affectation_postes',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('couleur', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_supervises', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'projets',
            },
        ),
        migrations.AddField(
            model_name='poste',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='workspaces.rack'),
        ),
    ]
