# Generated by Django 5.2.15 on 2026-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='superviseur',
            field=models.CharField(blank=True, help_text='Nom du superviseur', max_length=150, null=True),
        ),
    ]
