# Generated by Django 5.2.15 on 2026-07-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entite', models.CharField(help_text='Nom du modèle/table concerné', max_length=100)),
                ('entite_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': 'Journal des activités',
                'db_table': 'journal_activites',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['entite', 'entite_id'], name='journal_act_entite_fabd94_idx'), models.Index(fields=['date_action'], name='journal_act_date_ac_8e71ef_idx')],
            },
        ),
    ]
