# Generated by Django 5.2.15 on 2026-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('type_valeur', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('booleen', 'Booléen'), ('json', 'JSON')], default='texte', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'db_table': 'parametres',
            },
        ),
    ]
